### PR TITLE
Add support to build rpms directly from make

### PR DESCRIPTION
**Pull request by simo5**
This makes it simpler for me to try evolution-activiesync out w/o having to install devel libraries and splattering the filesystem of target machines.
May not be ideal yet, but better than nothing, le tme know if you are interested.

### CODE REVIEW

**Comment by dwmw2** [comment]
Please use macros such as %{_libdir} etc., and make it own %{_includedir}/eas-daemon. Isn't %make_install also deprecated? And the primary source should probably be GNOME not github?

**Comment by simo5** [comment]
Updated

**Comment by simo5** [comment]
Spec file should be better now

**Comment by gnomesysadmins** [comment]
Thank you for contributing to evolution-activesync!

evolution-activesync uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers/CodeContributionWorkflow
and follow the instructions there to upload your change to Bugzilla.

**Pull request closed without merging**
